##################################################################################
# PiLa_Code ######################################################################

alias "n"='cd ~/01_Notebook'
alias "w"='cd ~/02_Work/'
alias "t"='cd ~/03_Test/'
alias "r"='ranger'
alias "ud"='sudo apt update; sudo apt upgrade -y'

# Hide hostname and username in Terminal
export PS1="\W \$"

# Set Github ssh
eval $(ssh-agent -s) >/dev/null
ssh-add ~/.ssh/PiLaAcer >/dev/null 2>&1

